"""refresh_token_changes

Revision ID: 415fbf254e77
Revises: 
Create Date: 2019-08-16 23:17:38.392127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '415fbf254e77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uid', table_name='user_session')
    op.drop_table('user_session')
    op.add_column('user', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token')
    op.create_table('user_session',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_uid', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('access_token', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('refresh_token', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('uid', 'user_session', ['uid'], unique=True)
    # ### end Alembic commands ###
