"""Added_Scene_Score

Revision ID: 916f1e15f6a7
Revises: 
Create Date: 2019-11-28 00:14:00.238338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '916f1e15f6a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'next_scene_order')
    op.add_column('report_images', sa.Column('scene_user_response_score', sa.Float(), nullable=True))
    op.create_index('ix_user_id_story_id', 'story_purchase', ['user_id', 'story_id'], unique=False)
    op.add_column('story_scene_master_response', sa.Column('phoneme_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_scene_master_response', 'phoneme_filename')
    op.drop_index('ix_user_id_story_id', table_name='story_purchase')
    op.drop_column('report_images', 'scene_user_response_score')
    op.add_column('report', sa.Column('next_scene_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
