"""user_story_completed_uid

Revision ID: 99421479a2d6
Revises: e7c74df9e24d
Create Date: 2019-09-13 23:37:28.418793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99421479a2d6'
down_revision = 'e7c74df9e24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'report', 'user_story', ['user_story_id'], ['id'])
    op.create_foreign_key(None, 'report_images', 'story_scene_user_response', ['scene_user_response_id'], ['id'])
    op.create_foreign_key(None, 'report_images', 'report', ['report_id'], ['id'])
    op.create_foreign_key(None, 'scene_keyword', 'story_scene', ['story_scene_id'], ['id'])
    op.create_foreign_key(None, 'story_purchase', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'story_purchase', 'story', ['story_id'], ['id'])
    op.create_foreign_key(None, 'story_scene', 'story', ['story_id'], ['id'])
    op.create_foreign_key(None, 'story_scene_master_response', 'story_scene_speaker', ['story_scene_speaker_id'], ['id'])
    op.create_foreign_key(None, 'story_scene_speaker', 'story_scene', ['story_scene_id'], ['id'])
    op.create_foreign_key(None, 'story_scene_user_response', 'story_scene_speaker', ['story_scene_speaker_id'], ['id'])
    op.create_foreign_key(None, 'story_scene_user_response', 'user_story', ['user_story_id'], ['id'])
    op.create_foreign_key(None, 'user_purchase', 'user', ['user_id'], ['id'])
    op.add_column('user_story', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('user_story', sa.Column('uid', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user_story', ['uid'])
    op.create_foreign_key(None, 'user_story', 'story', ['story_id'], ['id'])
    op.create_foreign_key(None, 'user_story', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_story', type_='foreignkey')
    op.drop_constraint(None, 'user_story', type_='foreignkey')
    op.drop_constraint(None, 'user_story', type_='unique')
    op.drop_column('user_story', 'uid')
    op.drop_column('user_story', 'completed')
    op.drop_constraint(None, 'user_purchase', type_='foreignkey')
    op.drop_constraint(None, 'story_scene_user_response', type_='foreignkey')
    op.drop_constraint(None, 'story_scene_user_response', type_='foreignkey')
    op.drop_constraint(None, 'story_scene_speaker', type_='foreignkey')
    op.drop_constraint(None, 'story_scene_master_response', type_='foreignkey')
    op.drop_constraint(None, 'story_scene', type_='foreignkey')
    op.drop_constraint(None, 'story_purchase', type_='foreignkey')
    op.drop_constraint(None, 'story_purchase', type_='foreignkey')
    op.drop_constraint(None, 'scene_keyword', type_='foreignkey')
    op.drop_constraint(None, 'report_images', type_='foreignkey')
    op.drop_constraint(None, 'report_images', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    # ### end Alembic commands ###
