"""stripe

Revision ID: c43c10ac9b96
Revises: 
Create Date: 2019-12-19 22:46:22.542423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43c10ac9b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_card_id', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('last_four', sa.String(length=25), nullable=False),
    sa.Column('exp_month', sa.String(length=25), nullable=False),
    sa.Column('exp_year', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_card_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscription_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('stripe_plan_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_card_id'),
    sa.UniqueConstraint('stripe_charge_id'),
    sa.UniqueConstraint('stripe_invoice_id'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_table('current_subscription_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('subscription_contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_contract_id'], ['subscription_contracts.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_contract_id'),
    sa.UniqueConstraint('subscription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_subscription_contracts')
    op.drop_table('subscription_contracts')
    op.drop_table('subscriptions')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
