"""story_tables

Revision ID: e7c74df9e24d
Revises: b8412abf78ca
Create Date: 2019-08-31 16:36:42.110641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7c74df9e24d'
down_revision = 'b8412abf78ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('story_name', sa.String(length=75), nullable=True),
    sa.Column('story_desc', sa.Text(), nullable=True),
    sa.Column('story_length', sa.String(length=15), nullable=True),
    sa.Column('story_image', sa.String(length=255), nullable=True),
    sa.Column('difficulty_level', sa.String(length=25), nullable=True),
    sa.Column('genre', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('story_scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('scene_order', sa.Integer(), nullable=True),
    sa.Column('scene_keywords', sa.String(length=255), nullable=True),
    sa.Column('scene_type', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('scene_master_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('story_scene_id', sa.Integer(), nullable=False),
    sa.Column('master_audio_response', sa.String(length=255), nullable=True),
    sa.Column('master_text_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_scene_id'], ['story_scene.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('scene_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('story_scene_id', sa.Integer(), nullable=False),
    sa.Column('media_order', sa.Integer(), nullable=True),
    sa.Column('scene_image', sa.String(length=255), nullable=True),
    sa.Column('scene_audio', sa.String(length=255), nullable=True),
    sa.Column('scene_text', sa.Text(), nullable=True),
    sa.Column('scene_hint', sa.String(length=255), nullable=True),
    sa.Column('show_single', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['story_scene_id'], ['story_scene.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.alter_column('user', 'is_admin',
               existing_type=mysql.BIT(length=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=mysql.BIT(length=1),
               nullable=False)
    op.drop_table('scene_media')
    op.drop_table('scene_master_response')
    op.drop_table('story_scene')
    op.drop_table('story')
    # ### end Alembic commands ###
