DEBUG = 1
SECRET_KEY = '\x8a\x94R\x84\xf9\xb2\x91\x9d\x98w5&\x073\x8d\xb0\x92-\xb5U6\xb2\xf6\x84'
TOKEN_EXPIRY =200
REFRESH_TOKEN_EXPIRY =1440
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://Sanjay:sAnjAy@localhost/fluencyboxdb'
SQLALCHEMY_TRACK_MODIFICATIONS = False
FAILED_LOGIN_ATTEMPTS_LOCKOUT = 5
S3_KEY =  'AKIAUPHFJDPHPRSNXQZ2'
S3_SECRET = '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'
S3_BUCKET = 'fluencybox-dev'
S3_AVATAR_DIR = 'avatars'
S3_CONTENT_DIR = 'story_content'
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USE_TLS = False
MAIL_USERNAME = 'fluencybox19@gmail.com'
MAIL_PASSWORD = 'English@2019'
PASSWORD_RESET_TOKEN_EXPIRY =1800
S3_URL = 'https://fluencybox-dev.s3-us-west-1.amazonaws.com/'