DEBUG = 1
SECRET_KEY = '\x8a\x94R\x84\xf9\xb2\x91\x9d\x98w5&\x073\x8d\xb0\x92-\xb5U6\xb2\xf6\x84'
TOKEN_EXPIRY =200
REFRESH_TOKEN_EXPIRY =1440
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://chatterbox:Nachohiro10!@hanasudb2.ck2phw5jwjm2.us-west-1.rds.amazonaws.com:3306/hanasudb2'
SQLALCHEMY_TRACK_MODIFICATIONS = False
FAILED_LOGIN_ATTEMPTS_LOCKOUT =5
S3_KEY =  'AKIAUPHFJDPHPRSNXQZ2'
S3_SECRET = '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'
S3_BUCKET = 'fluencybox-dev'
S3_AVATAR_DIR = 'avatars'
DEFAULT_IMAGE = 'default_image.png'
S3_CONTENT_DIR = 'story_content'
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USE_TLS = False
MAIL_USERNAME = 'fluencybox19@gmail.com'
MAIL_PASSWORD = 'English@2019'
PASSWORD_RESET_TOKEN_EXPIRY =1800
S3_URL = 'https://fluencybox-dev.s3-us-west-1.amazonaws.com/'
S3_REGION = 'us-west-1'
SIGNED_URL_EXPIRY =300
STORY_IMAGES_DIR = 'story_images'
SPEAKER_IMAGES_DIR = 'speaker_images'
SPEAKER_AUDIO_DIR = 'speaker_audio'
MASTER_RESPONSE_AUDIO_DIR = 'master_response_audio'
USER_RESPONSE_AUDIO_DIR = 'user_response_audio'
REPORT_IMAGES_DIR = 'report_images'
STRIPE_API_KEY = 'sk_test_h1Nc5jxArm8Vuxq8k3V9gluF00BIyU1r08'
HANASU_PLAN_ID = 'plan_GGjaAEz7B0Oxhg'